DROP TABLE IF EXISTS PRODUCTINFO;
 
CREATE TABLE PRODUCTINFO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  productname VARCHAR(250) NOT NULL,
  type VARCHAR(250)  NULL,
  instockqty INT(20) NOT NULL,
  retailprice INT(20) NOT NULL,
  sku VARCHAR(250) NOT NULL
);